name: Enforce Commit Messages

on:
  push:
    branches:
      - main

jobs:
  enforce-commit-messages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Specify Node.js version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enforce commit message conventions
        run: |
          #!/bin/bash
          
          JIRA_PATTERN="JP-[0-9]+"
          
          # Get the range of commits in the push event
          RANGE="${{ github.event.before }}..${{ github.sha }}"
          
          # Iterate through commits in the push
          for commit in $(git log --format=%H $RANGE); do
            # Get commit message
            message=$(git log --format=%B -n 1 $commit)
            
            # Check if commit message contains a Jira ID
            if ! [[ $message =~ $JIRA_PATTERN ]]; then
              echo "Commit $commit does not contain a valid Jira ID."
              echo "Please include a Jira ID in your commit message in the format JP-xyz."
              exit 1  # Reject the push
            fi
          done
